const TaskActionType = {
	FAIL_REQUEST_TASK: "FAIL_REQUEST_TASK",

	REQUEST_TASK_TOGGLE_STATUS: "REQUEST_TASK_TOGGLE_STATUS",
	TASK_TOGGLE_STATUS: "TASK_TOGGLE_STATUS",

	REQUEST_TASK_ADD: "REQUEST_TASK_ADD",
	TASK_ADD: "TASK_ADD",
};

export default TaskActionType;
